### ISSUE TITLE
Code Review Notes

### ISSUE THREAD

**Issue by fiveSpeedMazdarati** [bsinner/quickNotes#3]
# Design/Code Review 1

### Reviewer: Luke

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| This is a clear synopsis of the application. It does not appear to have any slang or technical language, and is easily understandable. Excellent job. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | The screen design I've seen so far from the documnetation and the pages that are already live looks good and makes sense. I can't think of anything that's missing.|
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| *The database meets the "at least 1 one-to-many relationship" requirement. The database is simple, but it meets the needs of the application and is of good design. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages.  | It looks like everything is set up correctly. One screenshot of your test coverage shows 80% coverage of methods in the persistence package - maybe this is out of date, or there's a good reason things are only 80% covered.|

**Comment by bsinner** [comment]
Thank you for your feedback, the coverage picture must be out of date because the persistence tests show 100% coverage now.
